# declare a service object
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc-mysql
  labels:
    env: prod
    version: v1.1
    
# define and configure service to acces 80 port
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32406
    
    protocol: TCP
  
  selector:
    env: prod