apiVersion: v1
kind: ConfigMap
metadata:
 name: configmap-demo
data:
   # property-like keys; each key maps to a simple value
    MYSQLDB_USER: root
    MYSQLDB_ROOT_PASSWORD: "123456"
    MYSQLDB_DATABASE: bezkoder_db
    MYSQLDB_LOCAL_PORT: "3307"
    MYSQLDB_DOCKER_PORT: "3306"

    